### ISSUE TITLE
Add support for polymorphic relationships.

### ISSUE THREAD

**Issue by unravel-dev** [Rn86/Cobalt#1]
Amazing work man.
Something that in my opinion is a MUST in this library

```
auto ty = TypeOf<:BTestClass>();
ATestClass* a = new BTestClass(13);
auto info = TypeOf(*a); // or TypeOf(a)
// and having that return the actual type which is BTestClass
// this can easily be done by adding a virtual function inside the class
virtual TypeInfo vTypeOf() const
{
    return Cobalt::TypeOf<ATestClass>();
}
```

and having the TypeOf(const T& obj) call that. 
or maybe something else

It should also have some kind of way to ask a Type if it has some Base class

```
static void TypeOf(TypeRegistry<ATestClass> & reg)
{
    reg.Namespace("Cobalt");
    reg.Name("ATestClass");
        reg.Base<SomeBaseClass>();
    reg.Field("m_number", &ATestClass::m_number);
}
```

//somewhere later

```
auto ty = TypeOf<:ATestClass>();
bool hasBase = ty.HasBase<SomeBaseClass>(); // or
bool hasBase = ty.HasBase(TypeOf<SomeBaseClass>()); // or
bool kindOf = ty.KindOf<SomeBaseClass>(); // or
bool kindOf = ty.KindOf(TypeOf<SomeBaseClass>());
```

**Comment by Rn86** [comment]
Thank you for your comment. This library will be covering all your mentioned features and many more soon. My next commit with a lot of cleanups, typeinfo about base types, getting typeinfo from polymorphic objects, more flexible and natural way to obtain methods and other information from typeinfo, will be in few days. Getting typeinfo from pointer types (so you can work with heap while using Cobalt library), accesor and modifier information will be commited shortly after. User defines type entities (like events) integration in Cobalt library will be supported too. And there is more features that will be integrated later.
